#  **Tensors**
### Scalar tensors 0d
### Vectors tensors 1d
### Matrices tensors 2d
### Higher dimensions tensors +3d

In [ ]:
import torch
data =[1.0,2.0,3.0,4.0]
tensor_from_list = torch.tensor(data)
type(tensor_from_list)
tensor_from_list

tensor([1., 2., 3., 4.])

In [ ]:
### tensors of zeros
zeros_tensor = torch.zeros(3,3)
zeros_tensor


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
zeros_tensor.shape


torch.Size([3, 3])

In [ ]:
zeros_tensor.ndim

2

In [ ]:
### Tensors of one's
random_tensor = torch.rand(4,4)
random_tensor

tensor([[0.7969, 0.9557, 0.7455, 0.0804],
        [0.3988, 0.0428, 0.2624, 0.6142],
        [0.7080, 0.4137, 0.9418, 0.8625],
        [0.1470, 0.8237, 0.2787, 0.9960]])

In [ ]:
### Range of tensor
range_tensor = torch.arange(0,10)
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
step_tensor = torch.arange(0,10,step=2)
step_tensor

tensor([0, 2, 4, 6, 8])

In [ ]:
## Tensor from numpy arrays
import numpy as np
numpy_array = np.array([1.5,2.5,3.5])
tensor_from_numpy = torch.from_numpy(numpy_array)
tensor_from_numpy

tensor([1.5000, 2.5000, 3.5000], dtype=torch.float64)

In [ ]:
## Convert back to numpy to array
tensor_from_numpy.numpy()

array([1.5, 2.5, 3.5])

In [ ]:
## Control datatype
float_tensor = torch.tensor([1.0,2.0,3.0],dtype=torch.float32)
float_tensor

tensor([1., 2., 3.])

In [ ]:
## Integer
int_tensor = torch.tensor([1.0,2.0,3.0],dtype=torch.int32)
int_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
## boolean
bool_tensor = torch.tensor([1.0,0,1.0],dtype=torch.bool)
bool_tensor


tensor([ True, False,  True])

In [ ]:
## tensor shape
shape_tensor = torch.tensor([[1,2],[3,4],[5,6]])
shape_tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
shape_tensor.shape

torch.Size([3, 2])

In [ ]:
shape_tensor.ndim

2

In [ ]:
## tensor initialization
## sometimes we want to create a tensor with the same shape as an existing tensor
base_tensor = torch.ones(2,3)
base_tensor


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
new_tensor = torch.rand_like(base_tensor)
new_tensor

tensor([[0.5802, 0.4439, 0.9238],
        [0.9259, 0.9188, 0.7109]])

In [ ]:
zeros_like_tensor = torch.zeros_like(base_tensor)
zeros_like_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
## do the same with random numbers
rand_like_tensor = torch.rand_like(base_tensor)
rand_like_tensor

tensor([[0.1506, 0.1996, 0.3485],
        [0.7321, 0.1764, 0.4074]])

In [ ]:
## creating an identity matrix
indentity_tensor = torch.eye(3)
indentity_tensor

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
## fill a tensor with specific values
fill_tensor = torch.full((2,3),27)
fill_tensor

tensor([[27, 27, 27],
        [27, 27, 27]])

In [ ]:
## Tensor operations
## Since they are on the same shape we can add or subtract them
tensor_a = torch.tensor([1.0,2.0,3.0])
tensor_b = torch.tensor([4.0,5.0,6.0])
sum_tensor = tensor_a + tensor_b
sum_tensor

tensor([5., 7., 9.])

In [ ]:
## Diff tensors
diff_tensor = tensor_a - tensor_b
diff_tensor

tensor([-3., -3., -3.])

In [ ]:
## In place operations
## Meaning the result of the operation will all write the original torch.tensor
## In place addition
tensor_a.add_(tensor_b)
tensor_a

tensor([5., 7., 9.])

In [ ]:
tensor_a.mul_(tensor_b)
tensor_a

tensor([20., 35., 54.])

In [ ]:
## Broadcasting
## Allows you to perform operations on tensors with different shapes as long as they are compatible
tensor_c = torch.tensor([1,2,3])
tensor_d = torch.tensor([[1],[2],[3]])
broadcast_result = tensor_c + tensor_d
broadcast_result

tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

In [ ]:
matrix_a = torch.tensor([[1,2,3],[4,5,6]])
matrix_b = torch.tensor([[7,8],[9,10],[11,12]])
matmul_results = torch.matmul(matrix_a,matrix_b)
matmul_results

tensor([[ 58,  64],
        [139, 154]])

In [ ]:
## Dot product
vector_a = torch.tensor([1,2,3])
vector_b = torch.tensor([4,5,6])
dot_product = torch.dot(vector_a,vector_b)
dot_product

tensor(32)

In [ ]:
tensor_e = torch.arange(12)
tensor_e

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
reshaped_tensor = tensor_e.view(3,4)
reshaped_tensor

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
reshaped_tensor.shape

torch.Size([3, 4])

In [ ]:
## Flattering a tensor
## Sometimes we want to flatten amulti dimensional into a pne dimenensional tensor
flattened_tensor = reshaped_tensor.view(-1)
flattened_tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
flattened_tensor.shape

torch.Size([12])

In [ ]:
## Concatenate tensors
tensor_g = torch.tensor([[1,2],[3,4]])
tensor_h = torch.tensor([[5,6],[7,8]])


In [ ]:
tensor_g

tensor([[1, 2],
        [3, 4]])

In [ ]:
tensor_h

tensor([[5, 6],
        [7, 8]])

In [ ]:
concat_rows = torch.cat((tensor_g,tensor_h),dim=0)
concat_rows

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [ ]:
concat_rows.shape

torch.Size([4, 2])

In [ ]:
concat_cols = torch.cat((tensor_g,tensor_h),dim=1)
concat_cols

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [ ]:
concat_cols

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [ ]:
concat_cols.shape

torch.Size([2, 4])

In [ ]:
## indexing:allows you to retrieve specific elements or range of elements from a tensor
tensor_a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor_a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
## Lets say we want to retrieve the element in row one and column two
element = tensor_a[1,2]
element

tensor(6)

In [ ]:
## We can directly modify elemenrts of a tensor by assigning new values
tensor_a[2,1] = 9
tensor_a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 9, 9]])

In [ ]:
## Slicing
## First two rows and first two columns
sub_tensor = tensor_a[:2,:2]
sub_tensor

tensor([[1, 2],
        [4, 5]])

In [ ]:
## Extract the second row
second_row = tensor_a[1,:]
second_row

tensor([4, 5, 6])

In [ ]:
## Extract the third col
third_col = tensor_a[:,2]
third_col


tensor([3, 6, 9])

In [ ]:
## Slcing with step size
tensor_a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 9, 9]])

In [ ]:
step_rows = tensor_a[::2,:]
step_rows

tensor([[1, 2, 3],
        [7, 9, 9]])

In [ ]:
step_columns = tensor_a[:,::2]
step_columns

tensor([[1, 3],
        [4, 6],
        [7, 9]])

In [ ]:
## Masking
## We are going to create a mask where elements greater then five are going to be true.
mask = tensor_a>5
mask

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

In [ ]:
masked_tensor = tensor_a[mask]
masked_tensor

tensor([6, 7, 9, 9])

# **Automatic Differentiation**
## Gradients are crusial for updating model parameters during training
## In pytorch

In [ ]:
## Autograd automates the process of calculating gradients, in pytorch every tensor has a flag, requires_grad, if requires_grad is True pytorch will track all operation in the tensor and automatically compute gradients during back propagation.

x = torch.tensor([2.0,3.0],requires_grad=True)
x

tensor([2., 3.], requires_grad=True)

In [ ]:
y = x*3

In [ ]:
z = y.sum()

In [ ]:
y

tensor([6., 9.], grad_fn=<MulBackward0>)

In [ ]:
z

tensor(15., grad_fn=<SumBackward0>)

In [ ]:
z.backward()

In [ ]:
x.grad

tensor([3., 3.])

In [ ]:
## No gradients
with torch.no_grad():
  y = x*2
  print("y without gradient tracking:",y)

y without gradient tracking: tensor([4., 6.])


In [ ]:
## Resseting gradients to zero
x.grad.zero_()

tensor([0., 0.])

In [ ]:
z =(x ** 2).sum()

In [ ]:
z

tensor(13., grad_fn=<SumBackward0>)

In [ ]:
z.backward()

In [ ]:
## z = x[0]^2 +x[1]^2 w.r.t x -->2*x[0]+2*x[1]=2*2 , 2*3=4, 6
x.grad

tensor([4., 6.])